language:
  node_js
install:
  - npm install -g codecov
 
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
   - snyk test
    - snyk auth
  
  CODECOV_TOKEN="ffb9588d-71bd-4c80-ae84-bfc1ac3b8ae7"
